### ISSUE TITLE
font-url() & image-url() return backslash'd paths when building on Windows

### ISSUE THREAD

**Issue by twilczak** [fetch/node-sass-asset-functions#3]
When building on a windows machine, the paths produced by image-url and font-url functions return paths with backslashes, rather than paths with forward slashes. 
Normally this would be great, however when these paths are resolved by the browser the backslashes are encoded, and when it attempts to resolve those paths, a 404 is returned. 

There may be a workaround for this that I'm not seeing, but I think requiring 'path-posix' in place of 'path' would resolve the problem. 

Would be happy to submit a pull request - obviously testing would require a windows environment. 

Please let me know what you think.

**Comment by twilczak** [comment]
For reference, the following is a sample of the output when run on OSX & Linux

    @font-face {
        font-family: 'OpenSans-Regular-webfont';
        src: url('../fonts/OpenSans-Regular-webfont.eot');
        ...  
    }

And the following is produced on windows:

    @font-face {
        font-family: 'OpenSans-Regular-webfont';
        src: url('..\fonts\OpenSans-Regular-webfont.eot');
        ...  
    }

**Comment by twilczak** [comment]
I also did a quick test this morning with path-posix in place of path. 
The output was what I expected, though I only tested image-url and font-url, not the others.

**Comment by koenpunt** [comment]
`path-posix` seems too much overhead. I've simply replaced the backslash in a http path with a forward slash: 7b0d107458fa84d7a024fba72e94d9ce01d80188. Does that work for you?

**Comment by koenpunt** [comment]
And thanks for your report! I'm not using windows so I wouldn't find out about this on my own

**Comment by twilczak** [comment]
Thanks for the reply, and no problem. 
Im sure this will work, but would like to verify first thing Monday morning. (Assuming you haven't already tested the fix on win). 

Thanks again.

**Comment by twilczak** [comment]
@koenpunt This fix addresses the issue for me. 
Looking forward to the release. 
Thanks again!

**Comment by koenpunt** [comment]
Released version 0.0.9
